version: "3.8"
services:
  db:
    # Use a Postgres image with the pgvector extension available.
    # The `ankane/pgvector` image bundles pgvector for supported Postgres versions.
    image: ankane/pgvector
    restart: unless-stopped
    environment:
      # Match the backend defaults in README/main.py for easier local dev:
      POSTGRES_USER: dev_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sop_dev_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
